import { Inter } from "next/font/google";
import Head from "next/head";
import { Toaster } from "react-hot-toast";

import AuthPage from "../Components/Authentication/AuthPage";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Toaster />
        <AuthPage />
      </main>
    </>
  );
}
